import { contentDates, siteIdentity } from "./site-identity";

export const siteUrl = siteIdentity.url;
export const contentPublishedAt = contentDates.published;
export const contentUpdatedAt = contentDates.modified;

const commonProcess = [
  ["01", "Define the market question", "Specify the instrument, intended horizon and decision the research must support."],
  ["02", "Review the evidence", "Study price structure, liquidity, volatility, events and relevant primary information."],
  ["03", "Build balanced scenarios", "State the activation condition, material risks and the evidence that invalidates the view."],
  ["04", "Make risk visible", "Connect entry conditions, invalidation, quantity and permitted rupee risk before execution."],
];

export const seoServicePages = {
  stockMarketAdvisory: {
    slug: "stock-market-advisory-india",
    updated: "2026-08-21",
    eyebrow: "INDIAN STOCK MARKET ADVISORY",
    title: "Stock market advisory",
    accent: "built for Indian markets.",
    metaTitle: "Stock Market Advisory Firm in India | Trade Firm",
    metaDescription: "Explore Trade Firm stock market advisory in India across NIFTY, BANK NIFTY, options, futures, equities, intraday and swing with defined risk.",
    intro: "Trade Firm is an Indian stock market advisory and research firm focused on clear market context, actionable conditions and visible risk across actively followed NSE and BSE markets.",
    heroLabel: "ADVISORY COVERAGE",
    heroItems: ["NIFTY & BANK NIFTY", "OPTIONS & FUTURES", "EQUITIES", "INTRADAY & SWING"],
    heroNote: "Structured guidance across market segments, time horizons and defined-risk scenarios.",
    overviewEyebrow: "A PROFESSIONAL ADVISORY PROCESS",
    overviewTitle: "What to expect from a stock market advisory firm in India.",
    overviewText: "Useful advisory explains the scenario, the condition that activates a view, the point that invalidates it and the capital risk involved. Trade Firm organises every communication around those decisions.",
    cards: [
      { tag: "MARKET CONTEXT", title: "Research before a recommendation", text: "Index structure, sector behaviour, volatility, liquidity and relevant events are assessed before an actionable scenario is communicated.", points: ["Trend and market structure", "Important demand and supply zones", "Event and volatility context"] },
      { tag: "INDEX ADVISORY", title: "NIFTY and BANK NIFTY guidance", text: "Daily index scenarios connect previous-session references, the opening range, price confirmation and derivatives context.", points: ["Pre-market preparation", "Opening 15-minute context", "First-hour structure and review"] },
      { tag: "DERIVATIVES", title: "Options and futures advisory", text: "Instrument selection is connected to the underlying view, expiry, volatility, liquidity, position size and predefined invalidation.", points: ["Strike and expiry context", "Contract exposure", "Defined rupee-risk planning"] },
      { tag: "EQUITIES", title: "Intraday, swing and positional views", text: "Selected NSE and BSE equities are studied across suitable horizons using price structure, volume, sector strength and material developments.", points: ["Session-focused opportunities", "Multi-session structure", "Monitoring and exit conditions"] },
    ],
    deepDiveTitle: "How to judge whether an advisory service fits your needs.",
    deepDiveIntro: "Market coverage is only one part of the decision. Service format, communication standards and risk process must match the way you actually participate in the market.",
    deepDive: [
      { title: "Match the service to the horizon", text: "Intraday guidance requires active monitoring and session-specific loss limits. Swing or positional guidance must account for overnight gaps, broader invalidation and events across multiple sessions." },
      { title: "Separate buying power from risk capacity", text: "Broker margin does not show how much loss is financially manageable. A responsible process begins with permitted rupee risk and then tests entry, stop distance and quantity." },
      { title: "Review the complete client journey", text: "Evaluate identity, service scope, official communication, fees, cancellation terms and complaint channels. Avoid urgency, assured returns or selective profit screenshots as the main evidence." },
    ],
    processTitle: "One advisory standard from preparation to review.",
    processText: "The objective is not to produce the maximum number of calls. It is to keep each decision connected to research, risk and a repeatable review process.",
    process: commonProcess,
    priorityLinks: [
      { href: "/blogs/intraday-stock-market-advisory-checklist", label: "Intraday advisory checklist" },
      { href: "/nifty-bank-nifty-advisory", label: "NIFTY & BANK NIFTY advisory" },
      { href: "/options-derivatives-research", label: "Options & derivatives research" },
      { href: "/tools/risk-planner", label: "Risk Planner" },
    ],
    relatedBlogs: ["stock-market-advisory-firm-india-guide", "intraday-stock-market-advisory-checklist", "equity-research-advisory-process-india"],
    faqs: [
      ["What markets does Trade Firm stock market advisory cover?", "Coverage includes major NSE and BSE indices, index and stock options, futures, selected equities, intraday, swing, positional opportunities and IPO research."],
      ["Does stock market advisory remove trading risk?", "No. Advisory can improve structure and communication, but it cannot assure profit or remove losses, gaps, slippage or liquidity risk."],
      ["What information may an advisory view contain?", "Depending on the service, a view may include research rationale, market context, actionable conditions, invalidation, objectives, position-risk context and updates."],
      ["Is the same advisory suitable for every client?", "No. Capital, objectives, experience, horizon and ability to absorb loss differ. Service scope should be understood before acting."],
      ["How can I evaluate an advisory firm in India?", "Review its identity, applicable registration, service scope, research process, official payment channels, complaint process and risk communication."],
      ["How does intraday advisory differ from swing guidance?", "Intraday advisory uses session-specific structure, liquidity and loss limits, while swing guidance must also account for overnight gaps, multi-session events and wider invalidation."],
    ],
    keywords: ["stock market advisory firm in India", "stock market advisory services", "Indian stock market advisory", "stock advisory company India"],
  },

  stockMarketResearch: {
    slug: "stock-market-research-india",
    updated: "2026-08-21",
    eyebrow: "INDIAN MARKET RESEARCH",
    title: "Stock market research",
    accent: "that explains the decision.",
    metaTitle: "Stock Market Research Firm in India | Trade Firm",
    metaDescription: "Trade Firm provides Indian stock market research across indices, derivatives, equities and IPOs with clear rationale, scenarios and material risks.",
    intro: "Trade Firm is a stock market research firm in India focused on decision-ready analysis. Research should explain the evidence, identify what can invalidate a view and communicate material risks before discussing an objective.",
    heroLabel: "RESEARCH COVERAGE",
    heroItems: ["INDICES", "DERIVATIVES", "EQUITIES", "IPOS"],
    heroNote: "Price structure, financial evidence, market context and transparent risk communication.",
    overviewEyebrow: "RESEARCH WITH A PURPOSE",
    overviewTitle: "Indian stock market research with a visible rationale.",
    overviewText: "A chart level without context is difficult to evaluate. Our research formats connect the market question, evidence, scenario, invalidation and review in one consistent structure.",
    cards: [
      { tag: "INDEX RESEARCH", title: "Market structure and breadth", text: "Major NSE and BSE indices are studied through trend, opening behaviour, sector participation, volatility and important references.", points: ["Index and sector structure", "Breadth and leadership", "Volatility and event context"] },
      { tag: "DERIVATIVES RESEARCH", title: "Options and futures context", text: "Underlying research is connected with expiry, contract exposure, premium behaviour, liquidity and leverage risk.", points: ["Instrument mechanics", "Expiry and volatility", "Position-risk implications"] },
      { tag: "EQUITY RESEARCH", title: "Business and price evidence", text: "Selected companies are reviewed using financial quality, valuation, sector conditions, price structure and material developments.", points: ["Business and financial review", "Valuation and peer context", "Technical structure and risks"] },
      { tag: "IPO RESEARCH", title: "Offer and valuation analysis", text: "IPO research examines the company, issue structure, use of proceeds, financials, peer valuation and disclosed material risks.", points: ["Offer document review", "Valuation comparison", "Opportunity and downside scenarios"] },
    ],
    deepDiveTitle: "How a reader can evaluate research quality.",
    deepDiveIntro: "Good research is not a confident headline. It is traceable evidence, clear assumptions, balanced scenarios and a transparent update process.",
    deepDive: [
      { title: "Primary information comes first", text: "Company filings, exchange announcements, offer documents and regulatory disclosures are prioritised where relevant. Commentary adds context but should not replace the underlying source." },
      { title: "Facts and interpretation stay separate", text: "Financial numbers and contract specifications are observable. Valuation comfort, trend quality and scenario probability involve interpretation and should be labelled accordingly." },
      { title: "Every view needs a condition for change", text: "A price level, financial result, disclosure, valuation change or market event can weaken a thesis. Updating after new material evidence is part of a disciplined research process." },
    ],
    processTitle: "From a market question to a reviewable research view.",
    processText: "Research quality improves when the source, method, assumptions and limitations are clear enough for the reader to evaluate independently.",
    process: commonProcess,
    priorityLinks: [
      { href: "/stock-market-advisory-india", label: "Stock Market Advisory India" },
      { href: "/ipo-research", label: "IPO Research India" },
      { href: "/blogs/intraday-stock-market-advisory-checklist", label: "Intraday advisory checklist" },
      { href: "/equity-research", label: "Equity research" },
    ],
    relatedBlogs: ["equity-research-advisory-process-india", "ipo-research-checklist", "market-structure-before-a-trade"],
    faqs: [
      ["What does Trade Firm stock market research cover?", "Coverage includes Indian indices, derivatives, selected NSE and BSE equities, sectors, IPOs, price structure, volatility and risk management."],
      ["How is research different from personalised advisory?", "Research explains a market or security view for an intended audience. Personalised advisory may additionally consider objectives, financial situation and risk capacity within the applicable scope."],
      ["Which sources can support the research process?", "Relevant exchange data, company filings, offer documents, regulatory disclosures, price and volume information and documented market observations may be used."],
      ["How often is a research view updated?", "Frequency depends on the horizon. Intraday research may change within a session, while equity or IPO research may change after a material disclosure, result or valuation change."],
      ["Does research guarantee an outcome?", "No. Research works with available evidence and uncertainty. New information, volatility, liquidity and unexpected events can change outcomes."],
    ],
    keywords: ["stock market research firm India", "stock market research India", "equity research India", "Indian stock market research"],
  },

  niftyBankNifty: {
    slug: "nifty-bank-nifty-advisory",
    eyebrow: "INDEX ADVISORY & RESEARCH",
    title: "NIFTY and BANK NIFTY advisory",
    accent: "from pre-market to close.",
    metaTitle: "NIFTY & BANK NIFTY Advisory Services | Trade Firm",
    metaDescription: "Structured NIFTY and BANK NIFTY advisory covering pre-market context, opening range, price levels, derivatives context, invalidation and review.",
    intro: "Trade Firm organises NIFTY and BANK NIFTY advisory around a daily decision cycle: prepare the market context, observe the opening range, confirm the active scenario, define invalidation and review the close.",
    heroLabel: "DAILY INDEX FRAMEWORK",
    heroItems: ["PRE-MARKET", "15-MIN RANGE", "FIRST HOUR", "CLOSE REVIEW"],
    heroNote: "One research language across India's actively followed index derivatives.",
    overviewEyebrow: "DAILY INDEX DECISIONS",
    overviewTitle: "Index guidance built around changing conditions.",
    overviewText: "An index can move from trend to range or calm to event-driven volatility within one session. A useful view prepares more than one condition and states when waiting is preferred.",
    cards: [
      { tag: "PRE-MARKET", title: "Prepare the session map", text: "Previous highs, lows, close, overnight cues, scheduled events and likely gap context are reviewed before the opening bell.", points: ["Previous-session structure", "Global and event context", "Important round numbers"] },
      { tag: "OPENING RANGE", title: "Use the first 15 minutes", text: "Early acceptance, rejection and volatility establish the opening range and whether prepared levels remain active.", points: ["Opening high and low", "Gap acceptance or rejection", "Initial breadth and momentum"] },
      { tag: "FIRST HOUR", title: "Connect the broader structure", text: "The first-hour high, low and internal structure provide broader references for continuation, reversal or range conditions.", points: ["One-hour structure", "Demand and supply alignment", "Confirmation quality"] },
      { tag: "DERIVATIVES", title: "Add futures and options context", text: "Price structure is considered with expiry, volatility, liquidity and contract behaviour before expressing a market view.", points: ["Futures exposure", "Options premium context", "Defined-risk execution"] },
    ],
    deepDiveTitle: "What makes an index level actionable instead of decorative.",
    deepDiveIntro: "A useful level changes the decision. It connects market structure, confirmation, invalidation and a realistic instrument-risk plan.",
    deepDive: [
      { title: "Confluence improves context, not certainty", text: "Previous levels, round numbers, retracement areas and demand or supply zones can align near one price. Alignment can make an area relevant, but price still has to confirm the scenario." },
      { title: "BANK NIFTY needs constituent awareness", text: "BANK NIFTY can be influenced heavily by major banking stocks. Index price should be read with constituent behaviour, financial-sector breadth and event risk." },
      { title: "No-trade conditions protect the process", text: "When price is trapped between key levels, liquidity is poor or volatility becomes disorderly, waiting can be the most disciplined decision." },
    ],
    processTitle: "A repeatable index workflow for every session.",
    processText: "The 10X THINK framework keeps important levels, confirmation and invalidation connected instead of reacting to every small movement.",
    process: commonProcess,
    relatedBlogs: ["nifty-bank-nifty-advisory-process", "bank-nifty-options-risk-management", "market-structure-before-a-trade"],
    faqs: [
      ["What does NIFTY and BANK NIFTY advisory cover?", "It can cover pre-market context, important levels, opening structure, directional scenarios, derivatives context, invalidation, objectives and review."],
      ["Why use the first 15-minute range?", "It provides information about early acceptance, rejection and initial volatility. It is a reference, not a standalone signal."],
      ["How is the first-hour structure used?", "Its high, low and internal structure can provide broader references for trend, range or reversal conditions."],
      ["Can the view change during the session?", "Yes. A scenario should change when its stated evidence or invalidation changes, not merely because of normal price noise."],
      ["Are index options risk-free?", "No. Premium can change rapidly due to price, volatility, time decay and liquidity, and realised loss can differ because of gaps or slippage."],
    ],
    keywords: ["NIFTY advisory services", "BANK NIFTY advisory", "NIFTY options advisory", "BANK NIFTY options advisory India"],
  },

  optionsDerivatives: {
    slug: "options-derivatives-research",
    eyebrow: "OPTIONS & DERIVATIVES INDIA",
    title: "Options and derivatives research",
    accent: "with defined-risk thinking.",
    metaTitle: "Options & Derivatives Research in India | Trade Firm",
    metaDescription: "Professional options and derivatives research in India for NIFTY, BANK NIFTY and selected stocks covering strike, expiry, volatility and risk.",
    intro: "Trade Firm begins with the underlying market and then connects the view to strike, expiry, premium behaviour, liquidity and position risk. Direction alone is never treated as a complete options plan.",
    heroLabel: "DERIVATIVES INPUTS",
    heroItems: ["UNDERLYING", "STRIKE", "EXPIRY", "VOLATILITY & RISK"],
    heroNote: "Index and stock-derivatives context designed around the instrument actually being traded.",
    overviewEyebrow: "OPTIONS NEED MORE THAN DIRECTION",
    overviewTitle: "Connect five moving parts before considering a contract.",
    overviewText: "Option premium can change because of the underlying, implied volatility, time decay, liquidity and strike selection. Each view connects market research with product mechanics and execution risk.",
    cards: [
      { tag: "UNDERLYING VIEW", title: "Start with market structure", text: "NIFTY, BANK NIFTY or the selected stock is analysed before an option contract is considered.", points: ["Trend and important zones", "Opening and first-hour behaviour", "Confirmation and invalidation"] },
      { tag: "CONTRACT SELECTION", title: "Match strike and expiry", text: "Moneyness, time remaining, market depth and intended holding period influence contract selection.", points: ["Strike responsiveness", "Expiry and time decay", "Bid-ask spread and liquidity"] },
      { tag: "PREMIUM BEHAVIOUR", title: "Account for volatility", text: "Implied-volatility expansion or contraction can alter premium even when the directional market view remains broadly correct.", points: ["Event volatility", "Premium expansion and contraction", "Fast-market execution"] },
      { tag: "RISK CONTROL", title: "Size from permitted loss", text: "Quantity is tested against entry-to-stop distance and the maximum rupee risk allocated to the setup.", points: ["Premium-risk reference", "Order quantity", "Slippage and gap allowance"] },
    ],
    deepDiveTitle: "Why the contract must fit the market thesis.",
    deepDiveIntro: "Two traders can hold the same directional view and receive different outcomes because strike, expiry, entry timing, liquidity and size are different.",
    deepDive: [
      { title: "Moneyness changes responsiveness", text: "In-the-money, at-the-money and out-of-the-money contracts do not respond identically. A cheaper premium is not automatically lower risk, especially when spreads are wide." },
      { title: "Expiry changes the decision clock", text: "As expiry approaches, time remaining decreases and premium behaviour can become more sensitive. The expected holding period should fit the selected contract." },
      { title: "Stops need market and premium context", text: "A premium-only stop can be distorted by volatility, while an underlying-only invalidation may not control actual rupee loss. Both must be connected." },
    ],
    processTitle: "From underlying research to an executable derivatives scenario.",
    processText: "Selecting a contract first and searching for a market reason later reverses the professional decision process.",
    process: commonProcess,
    relatedBlogs: ["options-trading-advisory-india-framework", "bank-nifty-options-risk-management", "options-premium-volatility-context"],
    faqs: [
      ["Which options segments can Trade Firm cover?", "Coverage can include liquid index options and selected stock options, subject to service scope and market conditions."],
      ["Why can premium lose value when direction is correct?", "Implied volatility, time decay, strike sensitivity, liquidity and speed of the underlying move all affect premium."],
      ["What should an options view include?", "It may include the underlying scenario, contract context, activation condition, invalidation, premium-risk reference, quantity context and monitoring conditions."],
      ["Are near-expiry options suitable for everyone?", "No. Near-expiry contracts can reprice and decay rapidly. Experience, capital, liquidity and monitoring ability matter."],
      ["Does Trade Firm guarantee options profits?", "No. Options carry significant market, volatility, liquidity and execution risk. Outcomes cannot be guaranteed."],
    ],
    keywords: ["options research India", "options trading advisory India", "F&O advisory India", "derivatives research India"],
  },

  equityResearch: {
    slug: "equity-research",
    eyebrow: "EQUITY RESEARCH INDIA",
    title: "Equity research",
    accent: "from business quality to price structure.",
    metaTitle: "Equity Research & Stock Advisory in India | Trade Firm",
    metaDescription: "Explore Trade Firm equity research across NSE and BSE stocks, intraday, swing, positional opportunities and business-focused investment research.",
    intro: "Trade Firm connects company quality, sector context, valuation, price structure and event risk so that short-term and investment-oriented equity decisions use the right evidence for their horizon.",
    heroLabel: "EQUITY COVERAGE",
    heroItems: ["INTRADAY", "SWING", "POSITIONAL", "INVESTMENT RESEARCH"],
    heroNote: "Selected NSE and BSE equities studied with horizon-specific evidence and defined risk.",
    overviewEyebrow: "ONE STOCK, DIFFERENT DECISION CLOCKS",
    overviewTitle: "Equity research must match the intended holding period.",
    overviewText: "A strong business can still be a weak short-term setup at the wrong price, while momentum can exist without long-term investment quality. The research framework must match the decision being made.",
    cards: [
      { tag: "BUSINESS QUALITY", title: "Understand how the company earns", text: "Revenue drivers, margins, cash flow, debt, competition and management execution provide the business foundation.", points: ["Revenue and margin quality", "Cash flow and balance sheet", "Industry and management context"] },
      { tag: "VALUATION", title: "Compare price with evidence", text: "Valuation is studied relative to growth, quality, risk, history and relevant listed peers rather than through one ratio alone.", points: ["Peer comparison", "Growth and quality context", "Upside and downside assumptions"] },
      { tag: "PRICE STRUCTURE", title: "Study timing and invalidation", text: "Trend, volume, support, resistance and relative strength help translate a thesis into observable conditions.", points: ["Multi-timeframe trend", "Volume and liquidity", "Entry and invalidation zones"] },
      { tag: "EVENT RISK", title: "Track what can change the view", text: "Results, corporate actions, regulatory developments and sector events can materially alter price or business expectations.", points: ["Earnings calendar", "Exchange announcements", "Gap and liquidity risk"] },
    ],
    deepDiveTitle: "How equity research changes across intraday, swing and investment horizons.",
    deepDiveIntro: "The same stock can require different evidence, stop distance, position size and review frequency depending on the intended holding period.",
    deepDive: [
      { title: "Intraday decisions use session evidence", text: "Opening behaviour, liquidity, sector strength and immediate catalysts matter most when the position is expected to close in the same session." },
      { title: "Swing research connects several sessions", text: "Daily structure, event risk and sector leadership become more important when the thesis may develop over days or weeks." },
      { title: "Investment research requires business evidence", text: "Financial quality, competitive position, management, valuation and long-term risks deserve greater weight for investment-oriented decisions." },
    ],
    processTitle: "A horizon-specific equity research workflow.",
    processText: "Trade Firm avoids mixing a short-term price setup with a long-term investment thesis unless the evidence for both is stated separately.",
    process: commonProcess,
    relatedBlogs: ["equity-research-advisory-process-india", "intraday-stock-market-advisory-checklist", "intraday-vs-swing-research"],
    faqs: [
      ["Which stocks can Trade Firm research cover?", "Coverage may include selected liquid NSE and BSE-listed equities across large, mid and smaller companies where adequate information and liquidity are available."],
      ["Is intraday research the same as investment research?", "No. Intraday research prioritises session structure and liquidity, while investment research gives more weight to business quality, financials and valuation."],
      ["What can invalidate an equity thesis?", "Price structure, results, business deterioration, valuation change, regulatory events or new disclosures can weaken or invalidate a view."],
      ["Can a fundamentally strong stock decline?", "Yes. Valuation, liquidity, market conditions, earnings disappointment and unexpected events can cause significant declines."],
      ["Are small-cap stocks covered automatically?", "No. Coverage depends on information quality, liquidity, risk and whether the security fits the stated research process."],
    ],
    keywords: ["equity research India", "stock advisory India", "intraday stock research", "swing trading research India"],
  },

  ipoResearch: {
    slug: "ipo-research",
    updated: "2026-08-21",
    eyebrow: "IPO RESEARCH INDIA",
    title: "IPO research",
    accent: "beyond listing-day headlines.",
    metaTitle: "IPO Research & Analysis in India | Trade Firm",
    metaDescription: "Trade Firm IPO research reviews the business, financials, valuation, use of proceeds, peer comparison, offer structure and material risks.",
    intro: "An IPO is a business, an offer and a price—not only a grey-market headline. Trade Firm reviews the company, issue structure, financial quality, valuation, peers and disclosed risks before framing balanced scenarios.",
    heroLabel: "IPO RESEARCH FRAMEWORK",
    heroItems: ["BUSINESS", "FINANCIALS", "VALUATION", "OFFER & RISKS"],
    heroNote: "Independent offer-document analysis for Indian primary-market decisions.",
    overviewEyebrow: "READ THE OFFER, NOT ONLY THE HYPE",
    overviewTitle: "A disciplined IPO review starts with the prospectus.",
    overviewText: "Demand indicators can change quickly. Durable analysis begins with how the company earns, how the offer is structured, what valuation is being requested and which material risks are disclosed.",
    cards: [
      { tag: "BUSINESS MODEL", title: "Understand revenue and competition", text: "Products, customers, market position, concentration and competitive advantages are studied before the offer narrative is accepted.", points: ["Revenue model", "Customer and supplier concentration", "Industry structure and competition"] },
      { tag: "FINANCIAL QUALITY", title: "Review growth and cash flow", text: "Revenue, profit, margins, operating cash flow, debt and working capital are compared across the available reporting period.", points: ["Growth consistency", "Cash conversion", "Debt and working-capital risk"] },
      { tag: "OFFER STRUCTURE", title: "Separate fresh issue and OFS", text: "Use of proceeds, promoter dilution, selling shareholders and post-issue ownership help explain who receives the capital and why.", points: ["Fresh issue use", "Offer for sale", "Promoter holding and dilution"] },
      { tag: "VALUATION & RISK", title: "Compare price with listed peers", text: "Valuation is considered with growth, quality, scale, peer differences and material risks rather than through one headline multiple.", points: ["Peer valuation", "Assumption sensitivity", "Listing and post-listing risks"] },
    ],
    deepDiveTitle: "What an IPO research note should make clear.",
    deepDiveIntro: "A useful note separates observable information from interpretation and explains both the opportunity and the downside case.",
    deepDive: [
      { title: "Offer proceeds reveal the purpose", text: "Debt repayment, capacity expansion, working capital and general corporate purposes have different implications. An offer for sale does not add capital to the company." },
      { title: "Peer comparison needs adjustment", text: "Businesses can differ in margins, growth, debt, customer concentration and market position. A simple P/E comparison without those differences can mislead." },
      { title: "Listing demand is not business value", text: "Subscription and grey-market signals may affect short-term expectations but are not substitutes for business quality, valuation or post-listing risk analysis." },
    ],
    processTitle: "From prospectus review to balanced IPO scenarios.",
    processText: "The research process prioritises official offer information and clearly separates listing sentiment from the underlying business case.",
    process: commonProcess,
    priorityLinks: [
      { href: "/blogs/ipo-research-checklist", label: "IPO research checklist" },
      { href: "/blogs/ipo-valuation-peer-comparison", label: "IPO valuation & peer comparison" },
      { href: "/equity-research", label: "Equity research" },
      { href: "/research-methodology", label: "Research methodology" },
    ],
    relatedBlogs: ["ipo-research-checklist", "ipo-valuation-peer-comparison", "equity-research-advisory-process-india"],
    faqs: [
      ["What does Trade Firm IPO research review?", "The business, financial performance, offer structure, use of proceeds, promoters, valuation, listed peers and material risks may be reviewed."],
      ["Does IPO research guarantee listing gains?", "No. Subscription, market conditions, allotment, sentiment and unexpected events can produce outcomes different from the research scenario."],
      ["What is an offer for sale?", "In an OFS, existing shareholders sell shares and receive the proceeds. The company does not receive those proceeds."],
      ["Why compare an IPO with listed peers?", "Peer comparison provides valuation and operating context, but differences in growth, quality, debt and scale must be considered."],
      ["Can an IPO be good business but expensive?", "Yes. Business quality and offer valuation are separate questions; a strong company can still be offered at demanding assumptions."],
      ["Which official IPO documents should a reader check?", "Review the issuer's DRHP or RHP, relevant exchange filings and regulatory disclosures. Use those primary documents to verify the offer structure, financial information, promoters, proceeds and disclosed risks."],
    ],
    keywords: ["IPO research India", "IPO analysis India", "new IPO research", "IPO valuation analysis"],
  },
};

export const seoServicePageList = Object.values(seoServicePages);

export function servicePageMetadata(page) {
  const url = `${siteUrl}/${page.slug}`;
  return {
    title: page.metaTitle.replace(" | Trade Firm", ""),
    description: page.metaDescription,
    keywords: page.keywords,
    alternates: { canonical: url },
    openGraph: { title: page.metaTitle, description: page.metaDescription, url, siteName: "Trade Firm", locale: "en_IN", type: "website", images: [{ url: "/og-image.jpg", width: 1200, height: 630, alt: page.metaTitle }] },
    twitter: { card: "summary_large_image", title: page.metaTitle, description: page.metaDescription, images: ["/og-image.jpg"] },
  };
}
