import { siteIdentity } from "./site-identity";

export const trustPages = {
  trustCentre: {
    slug: "trust-centre",
    eyebrow: "TRADE FIRM TRUST CENTRE",
    title: "Clear identity.",
    accent: "Clear process. Visible risk.",
    metaTitle: "Trust Centre | Trade Firm Advisory & Research",
    metaDescription: "Review Trade Firm identity, contact channels, research methodology, editorial standards, risk disclosure and grievance process.",
    intro: "Use this centre to verify how Trade Firm communicates, researches, handles risk and receives questions or grievances before you use any service.",
    facts: [
      ["Main branch", "Thane, Maharashtra"],
      ["Second branch", "Navi Mumbai, Maharashtra"],
      ["Official email", siteIdentity.email],
      ["Official phone", siteIdentity.phoneDisplay],
    ],
    sections: [
      { title: "Identity and official contact", text: "Trade Firm publishes one official email address and phone number across the website. Service discussions and support should be confirmed through these channels.", points: ["Email: tradefirmindia@gmail.com", "Phone: +91 91377 25793", "Branches in Thane and Navi Mumbai, Maharashtra"] },
      { title: "Research and editorial standards", text: "Our methodology separates observable facts from interpretation, states important assumptions and gives risk and invalidation a visible place in every research format.", links: [["Read our research methodology", "/research-methodology"], ["Read our editorial policy", "/editorial-policy"]] },
      { title: "Risk, privacy and grievances", text: "Market outcomes cannot be assured. Review the risk disclosure, privacy practices, terms and complaint route before deciding whether a service is appropriate.", links: [["Risk disclosure", "/risk-disclosure"], ["Grievance redressal", "/grievance-redressal"], ["Privacy policy", "/privacy-policy"], ["Terms of use", "/terms-of-use"]] },
    ],
  },
  methodology: {
    slug: "research-methodology",
    eyebrow: "RESEARCH METHODOLOGY",
    title: "A research process",
    accent: "readers can evaluate.",
    metaTitle: "Stock Market Research Methodology | Trade Firm",
    metaDescription: "Learn how Trade Firm frames Indian stock market research using source review, market structure, balanced scenarios, invalidation and risk.",
    intro: "Trade Firm research begins with a defined market question and ends with a reviewable scenario. The method changes by instrument and horizon, but the evidence-to-risk sequence stays consistent.",
    facts: [["Step 01", "Define the decision"], ["Step 02", "Review evidence"], ["Step 03", "Build scenarios"], ["Step 04", "State risk and review"]],
    sections: [
      { title: "1. Define the market question", text: "We identify the security or index, intended horizon and decision the research must support. Intraday, swing, positional and investment questions are not treated as interchangeable.", points: ["Instrument and market segment", "Intended holding period", "Information needed for the decision"] },
      { title: "2. Review relevant evidence", text: "Depending on the topic, evidence may include price and volume, exchange information, company filings, offer documents, financial statements, contract specifications, volatility, liquidity and relevant events.", points: ["Primary information is preferred where available", "Material facts and interpretation are separated", "Source limitations are acknowledged"] },
      { title: "3. Build balanced scenarios", text: "A view should state what supports it, what activates it and what would weaken or invalidate it. Alternative and no-trade scenarios reduce pressure to force a conclusion.", points: ["Activation or confirmation condition", "Important upside and downside scenarios", "Clear invalidation or thesis-change condition"] },
      { title: "4. Connect the view with risk", text: "For market-action contexts, entry conditions, stop or invalidation, quantity and maximum rupee risk are considered together. Research cannot eliminate gaps, slippage, volatility or loss.", links: [["Open the Risk Planner", "/tools/risk-planner"], ["Read the risk disclosure", "/risk-disclosure"]] },
      { title: "5. Review and update", text: "The review frequency depends on the horizon. A view may be revisited after price invalidation, a material filing, results, a change in valuation, an event or new market evidence." },
    ],
  },
  editorial: {
    slug: "editorial-policy",
    eyebrow: "EDITORIAL POLICY",
    title: "Useful market content",
    accent: "without performance theatre.",
    metaTitle: "Editorial Policy | Trade Firm Research Desk",
    metaDescription: "Read Trade Firm editorial standards for accuracy, sourcing, corrections, independence, risk communication and evergreen market education.",
    intro: "This policy explains how the Trade Firm Research Desk plans, reviews, updates and corrects educational and research content published on tradefirm.in.",
    facts: [["Publisher", "Trade Firm Research Desk"], ["Primary audience", "Indian market participants"], ["Coverage", "Indices, derivatives, equities and IPOs"], ["Standard", "Evidence, balance and visible risk"]],
    sections: [
      { title: "Accuracy and sourcing", text: "Material facts are checked against relevant primary or authoritative information where available. We avoid presenting rumours, social-media claims or selective screenshots as sufficient evidence.", points: ["Company and exchange disclosures where relevant", "Official regulatory or product information", "Clear separation between facts and interpretation"] },
      { title: "Independence and commercial clarity", text: "Educational content is written to answer a market question, not to hide an advertisement. A service invitation does not change the requirement to discuss uncertainty, limitations and risk." },
      { title: "No assured outcomes", text: "Trade Firm does not publish language promising certain profit or risk-free returns. Historical examples and illustrative structures do not predict future performance." },
      { title: "Corrections and updates", text: "When a material factual issue is identified, the content should be corrected or clarified. Evergreen articles may be reviewed when rules, market structure, product features or important source information changes." },
      { title: "Reader feedback", text: "Readers can report a factual concern or request clarification through the official email. Include the page URL and the specific statement so the Research Desk can review it.", links: [["Contact the Research Desk", "/contact"], ["View author information", "/authors/trade-firm-research-desk"]] },
    ],
  },
  risk: {
    slug: "risk-disclosure",
    eyebrow: "MARKET RISK DISCLOSURE",
    title: "Understand the downside",
    accent: "before the opportunity.",
    metaTitle: "Stock Market Risk Disclosure | Trade Firm",
    metaDescription: "Read Trade Firm risk disclosure covering securities-market loss, derivatives leverage, volatility, liquidity, gaps, slippage and research limitations.",
    intro: "Investments and trading in securities markets involve risk. Research, advisory communication, tools and educational content cannot assure profit or prevent loss.",
    facts: [["Returns", "Never assured"], ["Capital", "Can decline"], ["Derivatives", "Leverage magnifies risk"], ["Execution", "Gaps and slippage can occur"]],
    sections: [
      { title: "General securities-market risk", text: "Market prices may move because of economic conditions, company developments, policy changes, liquidity, sentiment, events and information that was not available when a view was prepared." },
      { title: "Options and futures risk", text: "Derivatives can reprice rapidly and may not suit every participant. Leverage, time decay, implied volatility, expiry, margin changes and liquidity can materially affect outcomes.", points: ["Loss can occur quickly", "Margin is not maximum risk", "Near-expiry contracts can be highly sensitive", "Liquidity and bid-ask spreads matter"] },
      { title: "Gap, slippage and execution risk", text: "A stop or invalidation reference does not guarantee execution at that exact price. Fast markets, overnight gaps, circuit limits, order rejection and limited liquidity can increase realised loss." },
      { title: "Research limitations", text: "Research is based on information and assumptions available at a point in time. Data errors, interpretation differences and unexpected events can change a scenario. A view can be wrong even when the process is disciplined." },
      { title: "Personal responsibility", text: "Consider your objectives, knowledge, financial situation, time horizon and ability to absorb loss. Do not use borrowed money or funds required for essential needs to take market risk.", links: [["Read the research methodology", "/research-methodology"], ["Use the Risk Planner", "/tools/risk-planner"]] },
    ],
  },
  grievance: {
    slug: "grievance-redressal",
    eyebrow: "GRIEVANCE REDRESSAL",
    title: "A clear route",
    accent: "for questions and complaints.",
    metaTitle: "Grievance Redressal | Trade Firm",
    metaDescription: "Contact Trade Firm for service questions, complaints or correction requests using the official email and phone published on this page.",
    intro: "If you have a service concern, communication issue or factual correction request, contact Trade Firm through the official channels below with enough detail for review.",
    facts: [["Email", siteIdentity.email], ["Phone", siteIdentity.phoneDisplay], ["Main branch", "Thane, Maharashtra"], ["Second branch", "Navi Mumbai, Maharashtra"]],
    sections: [
      { title: "Step 1: Submit the concern", text: "Email tradefirmindia@gmail.com with your full name, registered mobile number, relevant date, service or webpage, and a clear description. Do not include account passwords, OTPs or unnecessary sensitive information." },
      { title: "Step 2: Keep supporting information", text: "Attach or preserve relevant official communication, invoices or screenshots where needed. This helps identify the exact interaction and reduces avoidable follow-up." },
      { title: "Step 3: Review and response", text: "Trade Firm will review the concern using available records and communicate the next step through the official contact details provided by the user. Complex matters can require additional information." },
      { title: "For website corrections", text: "Include the full page URL and quote the specific statement you believe is incorrect or unclear. The Research Desk will evaluate it under the editorial policy.", links: [["Read the editorial policy", "/editorial-policy"], ["Contact Trade Firm", "/contact"]] },
    ],
  },
  privacy: {
    slug: "privacy-policy",
    eyebrow: "PRIVACY POLICY",
    title: "Personal information",
    accent: "handled with purpose.",
    metaTitle: "Privacy Policy | Trade Firm",
    metaDescription: "Read how Trade Firm handles website enquiries, contact information, technical data, consent-based follow-up and privacy requests.",
    intro: "This policy explains the types of information tradefirm.in may receive, why it is used and how you can ask a privacy question. It applies to this website and official enquiry channels.",
    facts: [["Website", "tradefirm.in"], ["Contact", siteIdentity.email], ["Enquiries", "Consent-based follow-up"], ["Sensitive data", "Never send OTPs or passwords"]],
    sections: [
      { title: "Information you provide", text: "When you submit an enquiry, you may provide your name, mobile number, email, segment of interest, preferred callback time and message. Only provide information needed for the request." },
      { title: "How information is used", text: "Information may be used to respond to enquiries, explain service scope, maintain request records, improve website operation, handle complaints and meet applicable obligations." },
      { title: "Technical information", text: "Hosting, security and analytics systems may process standard technical information such as device, browser, IP address, referring page and website events. Availability depends on the tools configured by the website operator." },
      { title: "Sharing and protection", text: "Information may be processed by service providers required to operate hosting, communication or enquiry systems. Trade Firm does not ask for trading passwords, broker credentials or OTPs through the website." },
      { title: "Your privacy request", text: "You can ask a question or request correction of enquiry details through the official email. Some information may need to be retained where required for security, records or applicable obligations.", links: [["Contact Trade Firm", "/contact"], ["Read the terms of use", "/terms-of-use"]] },
    ],
  },
  terms: {
    slug: "terms-of-use",
    eyebrow: "TERMS OF USE",
    title: "Clear conditions",
    accent: "for using this website.",
    metaTitle: "Website Terms of Use | Trade Firm",
    metaDescription: "Review Trade Firm website terms covering educational content, research limitations, intellectual property, third-party links and acceptable use.",
    intro: "By using tradefirm.in, you acknowledge these website terms and the separate market-risk disclosure. Service-specific scope, if applicable, should be understood before onboarding.",
    facts: [["Content", "Information and research"], ["Outcomes", "Not guaranteed"], ["Use", "Lawful and personal"], ["Support", siteIdentity.email]],
    sections: [
      { title: "Website information", text: "Content is provided for general information, education and the stated research context. It is not a promise of a market outcome and should not be treated as risk-free or universally suitable." },
      { title: "No guarantee of availability or accuracy", text: "Reasonable efforts may be made to maintain useful information, but websites, data and market references can contain delays, errors or interruptions. Material decisions should be checked against relevant current sources." },
      { title: "Intellectual property", text: "Trade Firm branding, page design, original written content and proprietary frameworks may not be copied, republished or commercially redistributed without permission, except where law permits." },
      { title: "Third-party links", text: "Links to exchanges, regulators, social platforms or other third parties are provided for convenience or source context. Their availability, content and privacy practices are controlled by those parties." },
      { title: "Acceptable use and changes", text: "Do not misuse forms, attempt unauthorised access or interfere with website operation. These terms and website content may be updated when services, technology or applicable requirements change.", links: [["Read the risk disclosure", "/risk-disclosure"], ["Contact Trade Firm", "/contact"]] },
    ],
  },
};

export function trustPageMetadata(page) {
  const url = `${siteIdentity.url}/${page.slug}`;
  return {
    title: { absolute: page.metaTitle },
    description: page.metaDescription,
    alternates: { canonical: url },
    openGraph: { title: page.metaTitle, description: page.metaDescription, url, images: ["/og-image.jpg"] },
  };
}
